### ISSUE TITLE
if no username provided, error raised

### ISSUE THREAD

**Issue by JoeZ99** [emerleite/mongo-migrate#16]
in https://github.com/emerleite/mongo-migrate/blob/master/mongo_migrate#L114:

````shell
get_current_migration() {
    echo "`mongo $MONGO_HOST/$MONGO_DATABASE -u $MONGO_USR -p $MONGO_PWD --quiet ./get_current.js`"
}
````
if no username is provided, the script will attempt ```` mongo localhost/dbase -u -p```` and mongo will complain about that.

**Comment by emerleite** [comment]
Closed by #17
