### ISSUE TITLE
bc: command not found

### ISSUE THREAD

**Issue by pipo02mix** [emerleite/mongo-migrate#20]
When I try to run mongo migrate I have this output:
line 122: bc: command not found
line 128: bc: command not found

I have had to change the initial line from sh to bash because if not source and [[ comparisons fails.

**Comment by emerleite** [comment]
What is your S.O, @pipo02mix ?

**Comment by pipo02mix** [comment]
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by emerleite** [comment]
@pipo02mix I guess it only works with bash now. Do you have any ideas to work with basic shell?
